version: '3'

services:
  postgres:
    container_name: mydb
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  backend:
      image: danilosoftwares/backend-company-routes:latest
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DATABASE: ${POSTGRES_DATABASE}            
          POSTGRES_HOST: mydb          
      links:
          - "postgres"
      depends_on:
          - postgres                  
      ports:
        - "3003:3000"          
  frontend:
    image: danilosoftwares/frontend-company-routes:latest
    ports:
      - "3004:3000"
    depends_on:
      - backend        