CREATE TABLE IF NOT EXISTS clients (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  document VARCHAR(14) NOT NULL UNIQUE,
  positionx DECIMAL(10,8) NOT NULL,
  positiony DECIMAL(10,8) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(15) NOT NULL
);
